ffsasa/SWP391

booking-birthday-for-kids/src/main/resources/application.properties

Change application.properties

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Account.java

change some field of model

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Payment.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PaymentMethod.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Service.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Transaction.java

Payment, PaymentMethod, Transaction, Service model

Payment, PaymentMethod, Transaction, Service model

---

booking-birthday-for-kids/.github/workflows/cicd.yml
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/AccountController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/AccountRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/response/ResponseObj.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/AccountRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/AccountService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/AccountServiceImpl.java

sync with main branch and create package dto, repository, controller, service

sync with main branch

---

booking-birthday-for-kids/pom.xml
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/BookingBirthdayForKidsApplication.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/ApplicationConfig.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/FirebaseConfiguration.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/JwtFilter.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/JwtService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/SecurityConfiguration.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/SwaggerConfig.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/AccountController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/LoginRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/response/AuthenticationResponse.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/response/RegisterResponse.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Account.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/AccountRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/RoleRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/AccountService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/AccountServiceImpl.java
booking-birthday-for-kids/src/main/resources/birthday-party-for-kids-243a5-firebase-adminsdk-rc3cl-ec5faa7477.json

Complete config spring security, swagger, firebase and function register, login account

Configuration

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Account.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Inquiry.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Package.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PackageService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyDated.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Payment.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PaymentMethod.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Review.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Role.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Service.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Theme.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/UpgradeService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java

Complete relationships between Entities

Complete relationships between Entities

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyDated.java

Fix model v2

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ServicesController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/ServicesRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Services.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Transaction.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PaymentMethodRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/ServicesRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PaymentMethodService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ServicesService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentMethodServiceImpl.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java

CRUD Service

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PaymentMethodController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PaymentMethodRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Services.java

Fix Pricing Service

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PackageRequest.java

Fix packagerequest

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/VenueRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PartyBookingRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/ThemeRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/UpgradeServiceRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/VenueRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Add CRUD basic Venue, edit partyBooking Phone

Add CRUD basic Venue

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/VenueRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Create API addTheme and addPackage to Venue

Create API addTheme and addPackage to Venue

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PaymentMethodController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PaymentMethodRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PaymentMethod.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PaymentMethodRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PaymentMethodService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentMethodServiceImpl.java

Completed CRUD basic Payment Method

Completed CRUD basic Payment Method

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/UpgradeServiceController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PartyBookingRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/UpgradeServiceRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PartyBookingRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/UpgradeServiceRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/UpgradeServiceService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/UpgradeServiceServiceImpl.java

Add: CRUD UpgradeService and PartyBooking v1

Add: CRUD UpgradeService and PartyBooking v1

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/SecurityConfiguration.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/AccountController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/InquiryQuestionController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/InquiryReplyController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/InquiryReplyRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Inquiry.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/InquiryStatus.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/InquiryRepository.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/AccountService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/InquiryReplyService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/AccountServiceImpl.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/InquiryQuestionServiceImpl.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/InquiryReplyServiceImpl.java

Complete Inquiry V1

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PartyBookingRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/UpgradeServiceServiceImpl.java

Upload CRUD PartyBooking v2

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Package.java

Fix model package

---

booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PartyBookingRequest.java
booking-birthday-for-kids/src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Upload CRUD PartyBooking v3

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyDated.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/SlotInVenue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyDatedServiceImpl.java

Edit model base on new Database

Edit model base on new Database

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotInVenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/SlotInVenueRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/SlotInVenueRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/SlotInVenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotInVenueServiceImpl.java

add controller service of slot in venue v1

add controller service of slot in venue v1

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PartyDatedRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyDatedServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Fix class partydated request and partydateserviceimpl

Fix class partydated request and partydateserviceimpl

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/FirebaseConfiguration.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/AccountAdminController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/AccountController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/InquiryReplyController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageServiceController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ServicesController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotInVenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ThemeController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Account.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/AccountAdminService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/AccountService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/AccountAdminServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/AccountServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/FirebaseService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Add author, complete update image, fix something

Add author, complete update image, fix something

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/SlotRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Validate slot

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PartyBookingRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PartyDatedRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyDated.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Theme.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyDatedServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Edit PartyBooking, PartyDate, Theme, Venue

Edit PartyBooking, PartyDate, Theme, Venue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ServicesController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ThemeController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PackageRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Package.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Services.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Theme.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ServicesService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ThemeService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ThemeServiceImpl.java
src/main/resources/application.properties

update some function have image

update some function have image

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Package.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Payment.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Services.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Theme.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java

Add and edit attribute Description of Venue, Theme, Service, Package

Add and edit attribute Description of Venue, Theme, Service, Package

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Theme.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ThemeServiceImpl.java

fix theme description

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/InquiryQuestionController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/InquiryReplyController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

fix some bug

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotInVenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/SlotInVenue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/SlotInVenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotInVenueServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Add API check-slot-in-venue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PaymentController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PaymentMethodController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ServicesController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ThemeController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/TransactionController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PaymentRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/TransactionRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Payment.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Transaction.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PaymentMethodRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PaymentRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/ServicesRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/TransactionRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PaymentService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ServicesService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ThemeService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/TransactionService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentMethodServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ThemeServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/TransactionServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Complete basic CRUD Payment, Payment Method, Transaction, Complete up…
…date Package, Venue, Theme, Service. Complete create Venue

Complete basic CRUD Payment, Payment Method, Transaction, Complete up… …date Package, Venue, Theme, Service. Complete create Venue

---

pom.xml
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java

Add validation for the date parameter in the check-slot-in-venue API

Add validation for the date parameter in the check-slot-in-venue API

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Fix validate Slot

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

[Validate Timerange between slots successful]

Validate Timerange between slots successful

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/UpgradeServiceRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit update ParytBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ThemeController.java

Fix PutMapping ThemeController

Fix PutMapping ThemeController

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

fix update venue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Update Validate can not create in 00:00:00 - 07:59:59 and can not create with time start > time end

Update Validate can not create in 00:00:00 - 07:59:59 and can not create with time start > time end

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Complete api GetPackageVenueById, GetThemeVenueById

Complete api GetPackageVenueById, GetThemeVenueById

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Add API getSlotInVenueByVenue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Package.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PackageInVenue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Theme.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/ThemeInVenue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Add relationship ThemeInVenue, PackageInVenue in model

Add relationship ThemeInVenue, PackageInVenue in model

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/UpgradeServiceServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Edit some API

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Complete editing VenueService

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PartyBookingRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/UpgradeServiceServiceImpl.java

Edit API Create, Update of PartyBooking

Edit API Create, Update of PartyBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ReviewController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/ReplyReviewRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/ReviewRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Review.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/ReviewRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ReviewService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ReviewServiceImpl.java

add review

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ReviewController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ReviewService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ReviewServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java

Change Delete Service, partybooking, complete update/delete review

Change Delete Service, partybooking, complete update/delete review

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ReviewServiceImpl.java

fix update review

---

pom.xml
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageServiceController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PackageServiceRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageServiceService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceServiceImpl.java

Update Package PackageService

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/UpgradeServiceController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/UpgradeServiceService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/UpgradeServiceServiceImpl.java

Delete unnecessary import, API

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java

fix bug create package

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Complete GetPackageInVenue, GetThemeInVenue

Complete GetPackageInVenue, GetThemeInVenue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/AccountController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/AccountRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/exception/GlobalExceptionHandler.java

Use RestControllerAdvice

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

update discount package

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Added booking time validation must be at least 1 day before the event.

Added booking time validation must be at least 1 day before the event.

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Edit API CheckSlotInVenue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Update validate slot and add validate package

Update validate slot and add validate package

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ServicesController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Services.java

Validate pricing create-service, update-service

Validate pricing create-service, update-service

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Add API checkSlotInVenue for host

Add API checkSlotInVenue for host

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Remove unnecessary validate

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyDatedServiceImpl.java

Edit API getPartyBookingByPartyDate

Edit API getPartyBookingByPartyDate

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Account.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit API getAll of PartyBooking

Edit API getAll of PartyBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyDatedController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/BaseEntity.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyDatedService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyDatedServiceImpl.java

Delete Jsonignore in Base Entity, and delete API create PartyDated

Delete Jsonignore in Base Entity, and delete API create PartyDated

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/BookingBirthdayForKidsApplication.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ThemeController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Verify.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/VerifyRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ThemeService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/AccountServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ThemeServiceImpl.java
src/main/resources/application.properties
src/main/resources/static/emailTemplate.html

create addThemeInVenueByThemeId and validate lock account

create addThemeInVenueByThemeId and validate lock account

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyDated.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/UpgradeServiceRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyDatedServiceImpl.java

Update pricingtotal for Partybooking by Partydated

Update pricingtotal for Partybooking by Partydated

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyDatedServiceImpl.java

Update Partydate v2

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/PaymentConfig.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/SecurityConfiguration.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PaymentController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PaymentRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PaymentService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentMethodServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentServiceImpl.java

Payment Vnpay

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/SlotService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

update create slot

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Set active venue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Get package not add in venue, Get theme not add in venue

Get package not add in venue, Get theme not add in venue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Edit API CheckSlotInVenue for Customer

Edit API CheckSlotInVenue for Customer

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ThemeInVenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ThemeInVenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ThemeInVenueServiceImpl.java

Enable theme in venue, disable theme in venue

Enable theme in venue, disable theme in venue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageInVenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ServicesController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ThemeInVenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageInVenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ServicesService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ThemeInVenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageInVenueServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ThemeInVenueServiceImpl.java

Get by id for customer theme in venue, package in venue, service

Get by id for customer theme in venue, package in venue, service

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageInVenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageServiceController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyDatedController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageInVenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageServiceService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyDatedService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/SlotService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageInVenueServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyDatedServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Add api get by customer for slot, package, packageservice, partydate and create api to enable packageinvenue

Add api get by customer for slot, package, packageservice, partydate and create api to enable packageinvenue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java

Fix service image

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotInVenueServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Edit API Enable and Disable Venue

Edit API Enable and Disable Venue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Update package in venue in party booking

Update package in venue in party booking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PaymentController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PaymentMethodRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PaymentService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentMethodServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentServiceImpl.java

Cancel payment

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ReviewController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Review.java

Delete Ignore partybooking with review

Delete Ignore partybooking with review

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PaymentController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PaymentService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentServiceImpl.java

Change cancel payment from to cancel party booking

Change cancel payment from to cancel party booking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java

Change cancel name

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Detete comment in slot

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Add api cancel booking for host and customer

Add api cancel booking for host and customer

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/PartyBookingCronJob.java

Fix cronjob

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Add api complete partybooking and fix 2 api cancel partybooking

Add api complete partybooking and fix 2 api cancel partybooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java

Update post to put for api cancel

Update post to put for api cancel

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/AccountAdminController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/DashboardController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PaymentController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Review.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PaymentService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentServiceImpl.java

Fix something

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/AccountAdminController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/AccountRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PartyBookingRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/AccountAdminService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/AccountAdminServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

getAllCustomer,Host getAll party is complete

getAllCustomer,Host getAll party is complete

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java

delete authorize getAllPackage

delete authorize getAllPackage

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Room.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java

add class room

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Account.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Package.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PackageInBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PackageInVenue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyDated.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Review.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Services.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/SlotInVenue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/UpgradeService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Fix database

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/PartyBookingCronJob.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotInRoomController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Package.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyDated.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Room.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Services.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/SlotInRoom.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/TypeEnum.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/SlotInRoomRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/SlotInRoomService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/InquiryQuestionServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyDatedServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ReviewServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotInRoomServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

change something

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Account.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Dashboard.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Inquiry.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Package.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PackageInBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PackageInVenue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyDated.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Payment.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PaymentMethod.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Review.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Role.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Room.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Services.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/SlotInRoom.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/UpgradeService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java

Edit relationship database

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PartyBookingRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PackageInBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PaymentMethod.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Room.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentServiceImpl.java

Edit attribute of some Entity

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotInRoomController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/SlotInRoomRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/RoomRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/SlotInRoomRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageInVenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/SlotInRoomService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyDatedServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotInRoomServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Change SlotInVenue to SlotInRoom

Change SlotInVenue to SlotInRoom

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ReviewServiceImpl.java

Fix api CRUD review

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/InquiryQuestionServiceImpl.java

 Delete api in inquiry not use

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/InquiryQuestionController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/InquiryQuestionService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/InquiryQuestionServiceImpl.java

Add new api for send inquiry to change package

Add new api for send inquiry to change package

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ServicesController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/ServicesRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/RoomService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ServicesService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Fix to retake

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/RoomController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/RoomService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Add api get-slot-not-add-in-room-by-room-id

Add api get-slot-not-add-in-room-by-room-id

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageInBookingRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageInBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageInBookingServiceImpl.java

Create repository, service package in booking

Create repository, service package in booking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/RoomController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/RoomRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/RoomService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java

update create room, api get-slot-not-add-in-room

update create room, api get-slot-not-add-in-room

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Api get-all-party-booking-by-venue

Api get-all-party-booking-by-venue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java

fix typeEnum for create package

fix typeEnum for create package

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ServicesController.java

Fix api create,update service

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/RoomController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/RoomService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java

Api check-slot-in-venue-for-host

Api check-slot-in-venue-for-host

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/AccountAdminServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

customize venue by id

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/SlotRepository.java

Update repository for slot

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Switch api

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/RoomController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ServicesController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PartyBookingRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/RoomService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ServicesService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java

Fix api service, room

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/PartyBookingCronJob.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PartyBookingRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PackageInBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Payment.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PaymentMethod.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Review.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Role.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Room.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Services.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/SlotInRoom.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/UpgradeService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageInBookingRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PaymentRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/RoomRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit PartyBooking controller, Service, Repository, Request

Edit PartyBooking controller, Service, Repository, Request

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/SlotRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Fix package repository and api package, slot

Fix package repository and api package, slot

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

fix infinity recursion

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/RoomController.java

Fix api create room

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/RoomController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java

Fix api room,service

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java

Add error api room

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PartyBookingRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit PartyBooking Update APIs

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotInRoomController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/SlotInRoomService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotInRoomServiceImpl.java

Fix api slot in room

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/RoomController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/RoomService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java

fix check slot by customer

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/VenueController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/VenueService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

remove id for venue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/SlotRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Fix validate slot accept create slots in other account and not validate

Fix validate slot accept create slots in other account and not validate

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java

Validate date == null

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Fix create, update, delete slot

Fix create, update, delete slot

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/RoomController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/RoomService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java

Fix api create room, add api enable room

Fix api create room, add api enable room

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/RoomController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/RoomService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java

Fix api room

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PartyBookingRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit Create and UpdateOrganization of PartyBooking

Edit Create and UpdateOrganization of PartyBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/SlotRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/SlotService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Fix api for slot get

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/SlotRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/SlotService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Fix api slot get all get by id

Fix api slot get all get by id

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/SlotController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/SlotService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Fix api and create new api to enable slot

Fix api and create new api to enable slot

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java

Return message 202

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Fix some api for package

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

Complete fix api create package

Complete fix api create package

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

Filter package

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

filter package for host

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

Fix complete api update package and percent

Fix complete api update package and percent

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/SlotServiceImpl.java

Fix api create package

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Services.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Slot.java

Jsonignore account in slot and services

Jsonignore account in slot and services

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Delete propertity is unnecessary

Delete propertity is unnecessary

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit PartyBooking model and service

Edit PartyBooking model and service

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

Fix 3 api getallpackageforhost and get id

Fix 3 api getallpackageforhost and get id

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ServicesServicesImpl.java

Fix status

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

Fix api get all for host

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

Update package controller

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Create filter for PartyBooking

Create filter for PartyBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/request/PartyBookingRequest.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit filter

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

Fix get type package and active

 Fix get type package and active

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/VenueServiceImpl.java

Edit API Create PartyBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PartyBookingRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit filter for PartyBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentServiceImpl.java

Fix payment

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PaymentServiceImpl.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/RoomServiceImpl.java

Check slot in room with party booking status

Check slot in room with party booking status

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit API of PartyBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit API get for PartyBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PackageController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/PackageRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PackageService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

Add Api for package to get all package don't use in party booking

Add Api for package to get all package don't use in party booking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/PartyBookingCronJob.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

cancel by cronjob

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/SlotRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Paging partyBooking for host

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/dto/response/ResponseObjMeta.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Meta.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

add meta data

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

fix error 500 of paging

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit API Cancel PartyBooking for Customer

Edit API Cancel PartyBooking for Customer

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/PartyBookingController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Add Sort when get All Party Booking For Host

Add Sort when get All Party Booking For Host

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ReviewController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/PartyBooking.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Review.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/model/Venue.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/ReviewRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ReviewService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ReviewServiceImpl.java

Fix api review and add relationship review and venue

Fix api review and add relationship review and venue

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ReviewServiceImpl.java

Fix code review :

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit API delete PartyBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ReviewController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/repository/ReviewRepository.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ReviewService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ReviewServiceImpl.java

Filter api review

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/controller/ReviewController.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/ReviewService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/ReviewServiceImpl.java

Add api get all review for host

Add api get all review for host

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/PartyBookingCronJob.java

fix cronjob cancel

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/config/PartyBookingCronJob.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit API complete PartyBooking

Edit API complete PartyBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit API Update Basic Info

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/PartyBookingService.java
src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit API UpdatePackage of PartyBooking

Edit API UpdatePackage of PartyBooking

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PackageServiceImpl.java

Fix api get all package by partybooking id

Fix api get all package by partybooking id

---

src/main/java/com/bookingBirthday/bookingbirthdayforkids/service/impl/PartyBookingServiceImpl.java

Edit API Update Package for PartyBooking

Edit API Update Package for PartyBooking
